"""Subclass of gPersonEditDialog, which is generated by wxFormBuilder."""

import wx
import GeneratedGUI

# Implementing gPersonEditDialog
class AncPicDBgPersonEditDialog( GeneratedGUI.gPersonEditDialog ):
	def __init__( self, parent ):
		GeneratedGUI.gPersonEditDialog.__init__( self, parent )

	# Handlers for gPersonEditDialog events.
	def birthDateChanged( self, event ):
		# TODO: Implement birthDateChanged
		pass

	def deathDateChanged( self, event ):
		# TODO: Implement deathDateChanged
		pass

	def removeMotherLink( self, event ):
		# TODO: Implement removeMotherLink
		pass

	def removeFatherLink( self, event ):
		# TODO: Implement removeFatherLink
		pass

	def editPictureInfo( self, event ):
		# TODO: Implement editPictureInfo
		pass

	def addPicture( self, event ):
		# TODO: Implement addPicture
		pass

	def viewPicture( self, event ):
		# TODO: Implement viewPicture
		pass

	def removePicture( self, event ):
		# TODO: Implement removePicture
		pass


